# Category's
Category.create!(code: 'UC', name: 'Urban Connectivity')
Category.create!(code: 'S', name: 'Site')
Category.create!(code: 'E', name: 'Energy')
Category.create!(code: 'W', name: 'Water')
Category.create!(code: 'M', name: 'Materials')
Category.create!(code: 'IE', name: 'Indoor Environment')
Category.create!(code: 'CE', name: 'Cultural & Economic')
Category.create!(code: 'MO', name: 'Management & Operations')

# Criteria
Criterion.create!(name: 'Proximity to Infrastructure', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Load on Local Traffic Conditions', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Public Transportation', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Private Transportation', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Sewer & Waterway Contamination', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Acoustic Conditions', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Proximity to Amenities', category: Category.find_by_code('UC'))
Criterion.create!(name: 'Accessibility',category: Category.find_by_code('UC'))

Criterion.create!(name: 'Land Preservation', category: Category.find_by_code('S'))
Criterion.create!(name: 'Water Body Preservation', category: Category.find_by_code('S'))
Criterion.create!(name: 'Habitat Preservation', category: Category.find_by_code('S'))
Criterion.create!(name: 'Vegetation', category: Category.find_by_code('S'))
Criterion.create!(name: 'Desertification', category: Category.find_by_code('S'))
Criterion.create!(name: 'Rainwater Runoff', category: Category.find_by_code('S'))
Criterion.create!(name: 'Heat Island Effect', category: Category.find_by_code('S'))
Criterion.create!(name: 'Adverse Wind Conditions', category: Category.find_by_code('S'))
Criterion.create!(name: 'Noise Pollution', category: Category.find_by_code('S'))
Criterion.create!(name: 'Light Pollution', category: Category.find_by_code('S'))
Criterion.create!(name: 'Shading of Adjacent Properties', category: Category.find_by_code('S'))
Criterion.create!(name: 'Parking Footprint', category: Category.find_by_code('S'))
Criterion.create!(name: 'Shading', category: Category.find_by_code('S'))
Criterion.create!(name: 'Illumination', category: Category.find_by_code('S'))
Criterion.create!(name: 'Pathways', category: Category.find_by_code('S'))
Criterion.create!(name: 'Mixed Use', category: Category.find_by_code('S'))

Criterion.create!(name: 'Energy Demand Performance', category: Category.find_by_code('E'))
Criterion.create!(name: 'Energy Delivery Performance', category: Category.find_by_code('E'))
Criterion.create!(name: 'Fossil Fuel Conservation', category: Category.find_by_code('E'))
Criterion.create!(name: 'CO2 Emissions', category: Category.find_by_code('E'))
Criterion.create!(name: 'NOx, SOx, & Particulate Matter', category: Category.find_by_code('E'))

Criterion.create!(name: 'Water Consumption', category: Category.find_by_code('W'))

Criterion.create!(name: 'Regional Materials', category: Category.find_by_code('M'))
Criterion.create!(name: 'Responsible Sourcing of Materials', category: Category.find_by_code('M'))
Criterion.create!(name: 'Recycled Materials', category: Category.find_by_code('M'))
Criterion.create!(name: 'Materials Reuse', category: Category.find_by_code('M'))
Criterion.create!(name: 'Structure Reuse', category: Category.find_by_code('M'))
Criterion.create!(name: 'Design for Disassembly', category: Category.find_by_code('M'))

Criterion.create!(name: 'Thermal Comfort', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Natural Ventilation', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Mechanical Ventilation', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Illumination Levels', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Daylight', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Glare Control', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Views', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Acoustic Quality', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Low-Emitting Materials', category: Category.find_by_code('IE'))
Criterion.create!(name: 'Indoor Chemical & Pollutant Source Control', category: Category.find_by_code('IE'))

Criterion.create!(name: 'Heritage & Cultural Identity', category: Category.find_by_code('CE'))
Criterion.create!(name: 'Support of National Economy', category: Category.find_by_code('CE'))

Criterion.create!(name: 'Commissioning Plan', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Organic Waste Management', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Recycling Management', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Leak Detection', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Energy & Water Use Sub-metering', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Automated Control System', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Hospitality Management Plan', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Sustainability Education & Awareness Plan', category: Category.find_by_code('MO'))
Criterion.create!(name: 'Building Legacy', category: Category.find_by_code('MO'))

# Custom criteria for release 1
Category.create!(code: 'EX', name: 'Energy (existing buildings)')
Category.create!(code: 'WX', name: 'Water (existing buildings)')
Criterion.create!(name: 'Energy consumption', category: Category.find_by_code('EX'))
Criterion.create!(name: 'Water consumption', category: Category.find_by_code('WX'))

Certificate.create!(label: 'Letter of Conformance (currently not available)', certificate_type: :design_type, assessment_stage: :design_stage)
Certificate.create!(label: 'Final Design Certificate (currently not available)', certificate_type: :design_type, assessment_stage: :construction_stage)
Certificate.create!(label: 'Construction Certificate (currently not available)', certificate_type: :construction_type, assessment_stage: :construction_stage)
Certificate.create!(label: 'Operations Certificate', certificate_type: :operations_type, assessment_stage: :operations_stage)

Scheme.create!(label: 'Districts', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Districts', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Parks', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Parks', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Commercial', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Commercial', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Core + Shell', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Core + Shell', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Residential - Single', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Residential - Single', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Residential - Group', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Residential - Group', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Education', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Education', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Mosques', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Mosques', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Hotels', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Hotels', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Light Industry', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Light Industry', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Sports', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Sports', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Railways', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Railways', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Healthcare', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 0))
Scheme.create!(label: 'Healthcare', version: '3.0', certificate: Certificate.find_by(certificate_type: 0, assessment_stage: 1))
Scheme.create!(label: 'Construction', version: '3.0', certificate: Certificate.find_by(certificate_type: 1, assessment_stage: 1))
Scheme.create!(label: 'Operations', version: '3.0', certificate: Certificate.find_by(certificate_type: 2, assessment_stage: 2))
# todo: Scheme.create!(label: 'Workers\' Accommodation', version: '3.0')
# todo: Scheme.create!(label: 'Bespoke Schemes', version: '3.0')

operations_scheme = Scheme.find_by_label('Operations')
sc_op_ex1 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_name('Energy consumption'), weight: 5.2, code: 'EX.1')
sc_op_wx1 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_name('Water consumption'), weight: 16, code: 'WX.1')
Score.create!(score: -1, description: 'kWh<sub>year</sub> &gt; 25000',                  scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_ex1.criterion))
Score.create!(score: 0, description: '22500 &lt; kWh<sub>year</sub> &lte; 25000',        scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_ex1.criterion))
Score.create!(score: 1, description: '20000  &lt; kWh<sub>year</sub> &lte; 22500',        scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_ex1.criterion))
Score.create!(score: 2, description: '15000  &lt; kWh<sub>year</sub> &lte; 20000',        scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_ex1.criterion))
Score.create!(score: 3, description: 'kWh<sub>year</sub> &lte; 15000',                  scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_ex1.criterion))
Score.create!(score: -1, description: 'l<sub>year</sub> &gt; 5000',                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_wx1.criterion))
Score.create!(score: 0, description: '4000  &lt; l<sub>year</sub> &lte; 5000',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_wx1.criterion))
Score.create!(score: 1, description: '3000  &lt; l<sub>year</sub> &lte; 4000',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_wx1.criterion))
Score.create!(score: 2, description: '2000  &lt; l<sub>year</sub> &lte; 3000',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_wx1.criterion))
Score.create!(score: 3, description: 'l<sub>year</sub> &lte; 2000',                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: sc_op_wx1.criterion))
ec1 = Calculator.create!(name: 'Calculator::Dummy')
wc1 = Calculator.create!(name: 'Calculator::Dummy')
req1 = Requirement.create!(calculator: ec1, label: 'Energy calculator')
req2 = Requirement.create!(calculator: wc1, label: 'Water calculator')
req3 = Requirement.create!(label: 'Specifications and documentation regarding the available infrastructure showing that the existing structures can handle the additional load from the building')
SchemeCriterionRequirement.create!(scheme_criterion: sc_op_ex1, requirement: req1)
SchemeCriterionRequirement.create!(scheme_criterion: sc_op_wx1, requirement: req2)
SchemeCriterionRequirement.create!(scheme_criterion: sc_op_ex1, requirement: req3)
Field.create!(label: 'Yearly energy usage', name: 'kwh_year', calculator: ec1, datum_type: 'FieldDatum::IntegerValue')
Field.create!(label: 'Yearly water usage', name: 'l_year', suffix: 'liter', help_text: 'Please provide the yearly water usage in liter.', calculator: wc1, datum_type: 'FieldDatum::IntegerValue')


# sc_op_e1 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_code('E.1'), weight: 5.2)
# sc_op_e2 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_code('E.2'), weight: 5.2)
# sc_op_e3 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_code('E.3'), weight: 3.64)
# sc_op_e4 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_code('E.4'), weight: 4.55)
# sc_op_e5 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_code('E.5'), weight: 5.42)
# sc_op_e6 = SchemeCriterion.create!(scheme: Scheme.find_by_label('Operations'), criterion: Criterion.find_by_code('W.1'), weight: 16)
#
# operations_scheme = Scheme.find_by_label('Operations')
# criterion_e1 = Criterion.find_by_code('E.1')
# criterion_e2 = Criterion.find_by_code('E.2')
# criterion_e3 = Criterion.find_by_code('E.3')
# criterion_e4 = Criterion.find_by_code('E.4')
# criterion_e5 = Criterion.find_by_code('E.5')
# criterion_w1 = Criterion.find_by_code('W.1')
#
# Score.create!(score: -1, description: 'EPC<sub>nd</sub> &gt; 1.0',                  scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e1))
# Score.create!(score: 0, description: '0.8  &lt; EPC<sub>nd</sub> &lte; 1.0',        scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e1))
# Score.create!(score: 1, description: '0.7  &lt; EPC<sub>nd</sub> &lte; 0.8',        scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e1))
# Score.create!(score: 2, description: '0.6  &lt; EPC<sub>nd</sub> &lte; 0.7',        scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e1))
# Score.create!(score: 3, description: 'EPC<sub>nd</sub> &lte; 0.6',                  scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e1))
# Score.create!(score: -1, description: 'EPC<sub>del</sub> &gt; 1.0',                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e2))
# Score.create!(score: 0, description: '0.8  &lt; EPC<sub>del</sub> &lte; 1.0',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e2))
# Score.create!(score: 1, description: '0.7  &lt; EPC<sub>del</sub> &lte; 0.8',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e2))
# Score.create!(score: 2, description: '0.6  &lt; EPC<sub>del</sub> &lte; 0.7',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e2))
# Score.create!(score: 3, description: 'EPC<sub>del</sub> &lte; 0.6',                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e2))
# Score.create!(score: -1, description: 'EPC<sub>p</sub> &gt; 1.0',                   scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e3))
# Score.create!(score: 0, description: '0.8  &lt; EPC<sub>p</sub> &lte; 1.0',         scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e3))
# Score.create!(score: 1, description: '0.7  &lt; EPC<sub>p</sub> &lte; 0.8',         scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e3))
# Score.create!(score: 2, description: '0.6  &lt; EPC<sub>p</sub> &lte; 0.7',         scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e3))
# Score.create!(score: 3, description: 'EPC<sub>p</sub> &lte; 0.6',                   scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e3))
# Score.create!(score: -1, description: 'EPC<sub>CO2</sub> &gt; 1.0',                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e4))
# Score.create!(score: 0, description: '0.8  &lt; EPC<sub>CO2</sub> &lte; 1.0',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e4))
# Score.create!(score: 1, description: '0.7  &lt; EPC<sub>CO2</sub> &lte; 0.8',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e4))
# Score.create!(score: 2, description: '0.6  &lt; EPC<sub>CO2</sub> &lte; 0.7',       scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e4))
# Score.create!(score: 3, description: 'EPC<sub>co2</sub> &lte; 0.6',                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e4))
# Score.create!(score: -1, description: 'EPC<sub>NOx-SOx</sub> &gt; 1.0',             scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e5))
# Score.create!(score: 0, description: '0.8  &lt; EPC<sub>NOx-SOx</sub> &lte; 1.0',   scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e5))
# Score.create!(score: 1, description: '0.7  &lt; EPC<sub>NOx-SOx</sub> &lte; 0.8',   scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e5))
# Score.create!(score: 2, description: '0.6  &lt; EPC<sub>NOx-SOx</sub> &lte; 0.7',   scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e5))
# Score.create!(score: 3, description: 'EPC<sub>NOx-SOx</sub> &lte; 0.6',             scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_e5))
# Score.create!(score: -1, description: 'X &gt; 1.0',                                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_w1))
# Score.create!(score: 0, description: '0.87  &lt; X &lte; 1.0',                      scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_w1))
# Score.create!(score: 1, description: '0.73  &lt; X &lte; 0.87',                     scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_w1))
# Score.create!(score: 2, description: '0.6  &lt; X &lte; 0.73',                      scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_w1))
# Score.create!(score: 3, description: 'X &lte; 0.6',                                 scheme_criterion: SchemeCriterion.find_by(scheme: operations_scheme, criterion: criterion_w1))
