typology = 
  BuildingTypeGroup.find_or_create_by!(
    name: 'Typology', 
    visible: true
  )

[
  "Stadium",
  "Other",
  "Retail",
  "Restaurant",
  "Warehouse",
  "Workshop",
  "Industrial Process Building",
  "Other",
  "University / College",
  "Other",
  "Healthcare",
  "Industrial",
  "Entertainment",
  "Education",
  "Hospital",
  "Medical Research Centre",
  "Friday Mosque",
  "Water Park",
  "Small Station",
  "Major Station",
  "Other",
  "Multi-Purpose Hall",
  "Fitness/Leisure Center",
  "Swimming Pool Hall",
  "Shopping Mall",
  "Other",
  "Day Care",
  "School K-12",
  "Sports",
  "Media",
  "Mixed-Use",
  "Residential",
  "Other",
  "Healthcare Center/Outpatient Clinic",
  "Pharmacy/Laboratory",
  "Other",
  "Daily Prayers Mosque",
  "Other",
  "Mini Park",
  "Community Park",
  "Special-Use Park",
  "Other",
  "Workers Accommodation",
  "Other",
  "Home",
  "Other",
  "Hotel (5 Star)",
  "Hotel (1-4 Star)",
  "Service Apartments",
  "Other",
  "Public Building",
  "Other",
  "Apartments",
  "Other",
  "Education",
  "Entertainment",
  "Healthcare",
  "Industrial",
  "Media",
  "Sports",
  "Mixed-Use",
  "Residential",
  "Other",
  "Energy Center",
  "Airport terminal",
  "Bus Stops",
  "Car Park",
  "Port/Custom Terminal",
  "Other",
  "Office",
  "Commercial",
  "Expo Site"
].each { |name| BuildingType.find_or_create_by!(name: name, visible: true, building_type_group: typology) }

puts "Building Type Groups are added successfully.........."

