# U2 (Neighborhood Connectivity) => (FDC) CRITERION LEVELS
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "UC", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Neighborhood Connectivity"), name: "CRITERION LEVELS").update(html_text: "<ol><li><div class=\"table-responsive\"><table class=\"table table-bordered\"><colgroup><col/><col/></colgroup><tbody><tr><td><p><span>Levels</span></p></td><td><p><span>Neighborhood Connectivity Indicator (X) Indicator</span></p></td></tr><tr><td><p><span>0</span></p></td><td><p>X &lt; 0.7</p></td></tr><tr><td><p><span>1</span></p></td><td><p>0.7 <span>&le;</span> X &lt; 0.9</p></td></tr><tr><td><p><span>2</span></p></td><td><p>0.9 <span>&le;</span> X &lt; 1</p></td></tr><tr><td><p><span>3</span></p></td><td><p>X <span>&ge;</span> 1</p></td></tr></tbody></table></div></li></ol>")

# U2 (Neighborhood Connectivity)=> (LOC) CRITERION LEVELS
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "UC", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Neighborhood Connectivity"), name: "CRITERION LEVELS").update(html_text: "<ol><li><div class=\"table-responsive\"><table class=\"table table-bordered\"><colgroup><col/><col/></colgroup><tbody><tr><td><p><span>Levels</span></p></td><td><p><span>Neighborhood Connectivity Indicator (X) Indicator</span></p></td></tr><tr><td><p><span>0</span></p></td><td><p>X &lt; 0.7</p></td></tr><tr><td><p><span>1</span></p></td><td><p>0.7 <span>&le;</span> X &lt; 0.9</p></td></tr><tr><td><p><span>2</span></p></td><td><p>0.9 <span>&le;</span> X &lt; 1</p></td></tr><tr><td><p><span>3</span></p></td><td><p>X <span>&ge;</span> 1</p></td></tr></tbody></table></div></li></ol>")

# S11 (Walkability) => (FOC) ASSESSMENT PRINCIPLES
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "S", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Walkability"), name: "ASSESSMENT PRINCIPLES").update(html_text: "<ul><li>The project will <span>assess</span> <p>-\tThe extent to which pedestrians have access throughout the park.</p><p>-\tFixtures and features accessible to pathway users.</p></li><li>The Project will complete the <span>calculator</span> for S.11 Walkability to establish the <span>criterion level</span>.</li></ul>")
# ASSESSMENT
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "S", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Walkability"), name: "ASSESSMENT").update(html_text: "<p>The criterion requires <span>assessing</span> the extent and usability of footpaths throughout the park and the number of fixtures and features associated with the footpaths provided.</p><p>Subject to the type of park under assessment the <span>calculator</span> determines the indicators based on the type of footpaths provided, the adequacy and area of the available footpaths and the number, type and distances between features and fixtures provided and immediately associated with the footpaths provided in the park.</p><p>The criterion level is established based on the result of the indicators for S.11 Walkability.</p>")

# S11 (Walkability) => (LOC) ASSESSMENT PRINCIPLE
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "S", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Walkability"), name: "ASSESSMENT PRINCIPLES").update(html_text: "<ul><li>The project will <span>assess</span> <p>-\tThe extent to which pedestrians have access throughout the park.</p><p>-\tFixtures and features accessible to pathway users.</p></li><li>The Project will complete the <span>calculator</span> for S.11 Walkability to establish the <span>criterion level</span>.</li></ul>")
# ASSESSMENT
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "S", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Walkability"), name: "ASSESSMENT").update(html_text: "<p>The criterion requires <span>assessing</span> the extent and usability of footpaths throughout the park and the number of fixtures and features associated with the footpaths provided.</p><p>Subject to the type of park under assessment the <span>calculator</span> determines the indicators based on the type of footpaths provided, the adequacy and area of the available footpaths and the number, type and distances between features and fixtures provided and immediately associated with the footpaths provided in the park.</p><p>The criterion level is established based on the result of the indicators for S.11 Walkability.</p>")

#M5 (Cut & Fill Optimisation) => (FDC) ASSESSMENT PRINCIPLE
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "M", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Cut & Fill Optimisation"), name: "ASSESSMENT PRINCIPLES").update(html_text: "<ul><li>The Project will <span>assess</span> the overall weight of excavated materials reused onsite for filling purposes against the overall weight of excavated materials generated from site.</li><li>The Project will complete the <span>calculator</span> for M.5 Cut & Fill Optimization to establish the <span>criterion level</span>.</li></ul>")

# M5 (Cut & Fill Optimisation) => (LOC) ASSESSMENT PRINCIPLE
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "M", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Cut & Fill Optimisation"), name: "ASSESSMENT PRINCIPLES").update(html_text: "<ul><li>The Project will <span>assess</span> the overall weight of excavated materials reused onsite for filling purposes against the overall weight of excavated materials generated from site.</li><li>The Project will complete the <span>calculator</span> for M.5 Cut & Fill Optimization to establish the <span>criterion level</span>.</li></ul>")

# W2 (Water Reuse Performance) => (FDC) ASSESSMENT PRINCIPLE
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Water Reuse Performance"), name: "ASSESSMENT PRINCIPLES").update(html_text: "<ul><li>The Project will <span>assess</span> GSAS water performance coefficient of the water supply from recycling and reuse strategies (WPC<span>reuse</span>) in relation to the applicable GSAS benchmark.</li><li>The Project will complete <span>GSAS Water Suite&trade;</span> for W.2 Water Reuse Performance to establish the <span>criterion level</span>.</li></ul>")
# ASSESSMENT
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Water Reuse Performance"), name: "ASSESSMENT").update(html_text: "<p>The criterion requires assessing the design and installation of water reuse and recycling systems.  Such systems include the equipment, piping, storage tanks, and filtration system that collectively performs to collect, treat, store, and distribute treated water for reuse and recycling.  The assessment considers treated water from rainwater, greywater, cooling tower water, HVAC condensate drain water and community based Treated Sewage Effluent (TSE) supply. </p><p><span>GSAS</span><span> </span><span>Water</span><span> </span><span>Suite&trade;</span> determines the Water Performance Coefficient of the water supply from recycling and reuse strategies (WPC<span>reuse</span>). </p><div class=\"table-responsive\"><table class=\"table table-bordered\"><colgroup><col/><col/><col/></colgroup><tbody><tr><td rowspan=\"2\" style=\"vertical-align:middle;\"><p><span>WPC</span><span><sub>reuse</sub></span></p></td><td rowspan=\"2\" style=\"vertical-align:middle;\"><p><span>=</span></p></td><td><p><span>(W</span><span><sub>dem_occ</sub></span><span>+ W</span><span><sub>dem_out</sub></span><span>)- W</span><span><sub>reuse</sub></span></p></td></tr><tr><td><p><span>W</span><span><sub>ref_occ</sub></span><span>+ W</span><span><sub>ref_out</sub></span></p></td></tr></tbody></table></div><p>Where:</p><p>WPC<span><sub>reuse</sub></span> \tis the water reuse performance coefficient.</p><p>W<span><sub>dem_occ</sub></span> \tis the normalized water demand of the occupants for indoor use, in m3/yr.  </p><p>W<span><sub>dem_out</sub></span> \tis the normalized water demand of the outdoor use, in m3/yr.  </p><p>W<span><sub>reuse</sub></span>\tis the total amount of water reclaimed from various sources including rainwater, condensate water, greywater and TSE, in m3/yr.</p><p>W<span><sub>ref_occ</sub></span> \tis GSAS benchmark for the water demand of the occupants for indoor use for a specific building type, in m3/yr.</p><p>W<span><sub>ref_out</sub></span> \tis GSAS benchmark for the water demand of the outdoor use, in m3/yr.</p><p><br/>The <span>criterion level</span> is established based on the result of the WPC<span>reuse.</span></p><p> </p>")

# W2 (Water Reuse Performance) => (LOC) ASSESSMENT PRINCIPLE
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Water Reuse Performance"), name: "ASSESSMENT PRINCIPLES").update(html_text: "<ul><li>The Project will <span>assess</span> GSAS water performance coefficient of the water supply from recycling and reuse strategies (WPC<span>reuse</span>) in relation to the applicable GSAS benchmark.</li><li>The Project will complete <span>GSAS Water Suite&trade;</span> for W.2 Water Reuse Performance to establish the <span>criterion level</span>.</li></ul>")
# ASSESSMENT
SchemeCriterionText.find_by(scheme_criterion: SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Water Reuse Performance"), name: "ASSESSMENT").update(html_text: "<p>The criterion requires assessing the design and installation of water reuse and recycling systems.  Such systems include the equipment, piping, storage tanks, and filtration system that collectively performs to collect, treat, store, and distribute treated water for reuse and recycling.  The assessment considers treated water from rainwater, greywater, cooling tower water, HVAC condensate drain water and community based Treated Sewage Effluent (TSE) supply. </p><p><span>GSAS</span><span> </span><span>Water</span><span> </span><span>Suite&trade;</span> determines the Water Performance Coefficient of the water supply from recycling and reuse strategies (WPC<span>reuse</span>). </p><div class=\"table-responsive\"><table class=\"table table-bordered\"><colgroup><col/><col/><col/></colgroup><tbody><tr><td rowspan=\"2\" style=\"vertical-align:middle;\"><p><span>WPC</span><span><sub>reuse</sub></span></p></td><td rowspan=\"2\" style=\"vertical-align:middle;\"><p><span>=</span></p></td><td><p><span>(W</span><span><sub>dem_occ</sub></span><span>+ W</span><span><sub>dem_out</sub></span><span>)- W</span><span><sub>reuse</sub></span></p></td></tr><tr><td><p><span>W</span><span><sub>ref_occ</sub></span><span>+ W</span><span><sub>ref_out</sub></span></p></td></tr></tbody></table></div><p>Where:</p><p>WPC<span><sub>reuse</sub></span> \tis the water reuse performance coefficient.</p><p>W<span><sub>dem_occ</sub></span> \tis the normalized water demand of the occupants for indoor use, in m3/yr.  </p><p>W<span><sub>dem_out</sub></span> \tis the normalized water demand of the outdoor use, in m3/yr.  </p><p>W<span><sub>reuse</sub></span>\tis the total amount of water reclaimed from various sources including rainwater, condensate water, greywater and TSE, in m3/yr.</p><p>W<span><sub>ref_occ</sub></span> \tis GSAS benchmark for the water demand of the occupants for indoor use for a specific building type, in m3/yr.</p><p>W<span><sub>ref_out</sub></span> \tis GSAS benchmark for the water demand of the outdoor use, in m3/yr.</p><p><br/>The <span>criterion level</span> is established based on the result of the WPC<span>reuse.</span></p><p> </p>")

# MO3 incentive 0.5 -> 2.0
SchemeCriterionIncentive.find_by(scheme_criterion: SchemeCriterion.find_by(name: "Facility Management", number: 3, scheme_category: SchemeCategory.find_by(code: "MO", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation: false))), label: 'GSAS Accredited Facility Management Service Provider (+2%)').update(incentive_weight: 2.0)


# M5 (Cut & Fill Optimisation) -> LOC
requirements__M5_LOC = ['A narrative explaining the approach undertaken for the criterion assessment and highlighting the basis of any assumptions.', 'Evidence of total weight of predicted excavated materials as well as areas to be filled as per design, such as bill of quantities or cost estimates.', 'Relevant drawings and specifications showing the areas that to be excavated on-site.', 'Relevant drawings and specifications showing the areas that to be filled with the excavated materials.', 'Relevant documents and specifications showing how project secures the needed fill materials from off-site sources in case of needed.', 'M.5 Cut & Fill Optimization Calculator.']

SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "M", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)), name: "Cut & Fill Optimisation").requirements.each do |requirement|
  index = requirement.display_weight
  requirement.update(name: requirements__M5_LOC[index-1])
end

# M5 (Cut & Fill Optimisation) -> FDC
requirements__M5_FDC = ['A narrative explaining any updates or changes in the criterion assessment.', 'Evidence of the total amount of excavated materials generated on-site excerpts of up to date monthly certification approved by the Client (BOQ format).', 'Evidence of reusing excavated materials from on- or off-site sources such as Materials Approval Request (MAR) and excerpts of up to date monthly certification approved by the Client (BOQ format).', 'Relevant as-built drawings and specifications showing the reused excavated and filled areas.', 'Collection and delivery invoices or monthly logs issued by the transporter or destination site/facility, showing the quantities per type of material.', 'Updated M.5 Cut & Fill Optimization Calculator.']

SchemeCriterion.find_by(scheme_category: SchemeCategory.find_by(code: "M", scheme: Scheme.find_by(name: "Parks", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)), name: "Cut & Fill Optimisation").requirements.each do |requirement|
  index = requirement.display_weight
  requirement.update(name: requirements__M5_FDC[index])
end
