# Add/Edit title of Owners
Owner.find_by(name: 'Aspire Zone Foundation')&.update(name: "Aspire Zone Foundation (AZF)")
Owner.find_by(name: 'Hamad Medical Corporation')&.update(name: "Hamad Medical Corporation (HMC)")
Owner.find_by(name: 'New Port Project')&.update(name: "New Port Project (NPP)")
Owner.find_by(name: 'Qatar Foundation')&.update(name: "Qatar Foundation (QF)")
Owner.find_by(name: 'Qatar Rail')&.update(name: "Qatar Rail (QR)")
Owner.find_by(name: 'Supreme Committee for Delivery and Legacy')&.update(name: "Supreme Committee for Delivery & Legacy (SC)")
Owner.find_or_create_by(name: 'Barwa', governmental: true)
Owner.find_or_create_by(name: 'Katara Hospitality', governmental: true)
Owner.find_or_create_by(name: 'Milaha Maritime & Logistics', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Commerce and Industry', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Communications and Information Technology', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Culture', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Defense', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Education and Higher Education', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Endowments and Islamic Affairs', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Environment and Climate Change', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Finance', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Interior', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Justice', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Labor', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Municipality', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Public Health', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Social Development and Family', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Sports and Youth', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Transport', governmental: true)
Owner.find_or_create_by(name: 'Ministry of Sports and Youth', governmental: true)
Owner.find_or_create_by(name: 'Primary Health Care Corporation (PHCC)', governmental: true)
Owner.find_or_create_by(name: 'Private Sector', governmental: true)
Owner.find_or_create_by(name: 'Qatar Company for Airport Operations & Management (MATAR)', governmental: true)
Owner.find_or_create_by(name: 'Qatar Economic Zone Company (Manateq)', governmental: true)
Owner.find_or_create_by(name: 'Qatar Energy (QE)', governmental: true)
Owner.find_or_create_by(name: 'Qatar General Electricity & Water Corporation (KAHRAMAA)', governmental: true)
Owner.find_or_create_by(name: 'Qatar Museums (QM)', governmental: true)
Owner.find_or_create_by(name: 'Qatar University (QU)', governmental: true)
Owner.find_or_create_by(name: 'QETAIFAN Projects', governmental: true)
Owner.find_or_create_by(name: 'QTerminals', governmental: true)

# Edit locations
Location.find_by(country: "United Arab Emirates")&.update(list: ["Abu Dhabi", "Ajman", "Dubai", "Fujairah"])

# Update country of projects.
Project.where('code ILIKE ?', '%-QA-%').update_all(country: 'Qatar')
