# New checklist scheme 'Energy Centers' under Design & Build, 2019.

Scheme.find_or_create_by!(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)

Scheme.find_or_create_by!(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)

DevelopmentTypeScheme.find_or_create_by!(scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation: false), development_type: DevelopmentType.find_by(name: "Single use building, new", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:design_type], assessment_stage: Certificate.assessment_stages[:design_stage], gsas_version: "2019")))

SchemeCategory.find_or_create_by!(scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false), code: "G", name: "Generic", impacts: "", mitigate_impact: "", shared: false, display_weight: 1, is_checklist: true)

SchemeCategory.find_or_create_by!(scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false), code: "G", name: "Generic", impacts: "", mitigate_impact: "", shared: false, display_weight: 1, is_checklist: true)

SchemeCriterion.find_or_create_by!(name: "Checklist Specific", number: 1, scores_a: YAML.load("[[1, 1.0]]\n"), minimum_score_a: 0, maximum_score_a: 1, minimum_valid_score_a: 0, weight_a: 1, is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false)))
SchemeCriterion.find_or_create_by!(name: "Checklist Specific", number: 1, scores_a: YAML.load("[[1, 1.0]]\n"), minimum_score_a: 0, maximum_score_a: 1, minimum_valid_score_a: 0, weight_a: 1, is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false)))

SchemeCriterionBox.find_or_create_by!(scheme_criterion: SchemeCriterion.find_by(name: "Checklist Specific", is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false))), label: 'Targeted Checklist Status', display_weight: 1)
SchemeCriterionBox.find_or_create_by!(scheme_criterion: SchemeCriterion.find_by(name: "Checklist Specific", is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false))), label: 'Submitted Checklist Status', display_weight: 2)
SchemeCriterionBox.find_or_create_by!(scheme_criterion: SchemeCriterion.find_by(name: "Checklist Specific", is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:letter_of_conformance], renovation:false))), label: 'Achieved Checklist Status', display_weight: 3)
SchemeCriterionBox.find_or_create_by!(scheme_criterion: SchemeCriterion.find_by(name: "Checklist Specific", is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false))), label: 'Targeted Checklist Status', display_weight: 1)
SchemeCriterionBox.find_or_create_by!(scheme_criterion: SchemeCriterion.find_by(name: "Checklist Specific", is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false))), label: 'Submitted Checklist Status', display_weight: 2)
SchemeCriterionBox.find_or_create_by!(scheme_criterion: SchemeCriterion.find_by(name: "Checklist Specific", is_checklist: true, scheme_category: SchemeCategory.find_by(code: "G", is_checklist: true, scheme: Scheme.find_by(name: "Energy Centers", gsas_document: "GSAS Building Typologies_Assessment_2019_14.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:design_type], certification_type: Certificate.certification_types[:final_design_certificate], renovation:false))), label: 'Achieved Checklist Status', display_weight: 3)
