requirement_1_for_scheme_criterion_id_3335 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3335, scheme_criterion: SchemeCriterion.find_by(id: 3335))
requirement_2_for_scheme_criterion_id_3335 = Requirement.create!(name: "Executive Summary for On-Site Measurements of noise levels.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3335, scheme_criterion: SchemeCriterion.find_by(id: 3335))
requirement_3_for_scheme_criterion_id_3335 = Requirement.create!(name: "Building layout with specifications for spaces exposed to noise generating sources.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3335, scheme_criterion: SchemeCriterion.find_by(id: 3335))
requirement_4_for_scheme_criterion_id_3335 = Requirement.create!(name: "Noise generation sources details and specifications.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3335, scheme_criterion: SchemeCriterion.find_by(id: 3335))
requirement_1_for_scheme_criterion_id_3336 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3336, scheme_criterion: SchemeCriterion.find_by(id: 3336))
requirement_2_for_scheme_criterion_id_3336 = Requirement.create!(name: "Executive Summary for On-Site Measurements of noise levels.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3336, scheme_criterion: SchemeCriterion.find_by(id: 3336))
requirement_3_for_scheme_criterion_id_3336 = Requirement.create!(name: "Building layout with specifications for spaces exposed to noise generating sources.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3336, scheme_criterion: SchemeCriterion.find_by(id: 3336))
requirement_4_for_scheme_criterion_id_3336 = Requirement.create!(name: "Noise generation sources details and specifications.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3336, scheme_criterion: SchemeCriterion.find_by(id: 3336))
requirement_1_for_scheme_criterion_id_3337 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3337, scheme_criterion: SchemeCriterion.find_by(id: 3337))
requirement_2_for_scheme_criterion_id_3337 = Requirement.create!(name: "Executive Summary for On-Site Measurements for air pollutants including the trend logs and data analysis")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3337, scheme_criterion: SchemeCriterion.find_by(id: 3337))
requirement_3_for_scheme_criterion_id_3337 = Requirement.create!(name: "Indoor Air Quality Procedure (IAQP), if applicable.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3337, scheme_criterion: SchemeCriterion.find_by(id: 3337))
requirement_1_for_scheme_criterion_id_3338 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3338, scheme_criterion: SchemeCriterion.find_by(id: 3338))
requirement_2_for_scheme_criterion_id_3338 = Requirement.create!(name: "Executive Summary for On-Site Measurements for air pollutants including the trend logs and data analysis")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3338, scheme_criterion: SchemeCriterion.find_by(id: 3338))
requirement_3_for_scheme_criterion_id_3338 = Requirement.create!(name: "Indoor Air Quality Procedure (IAQP), if applicable.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3338, scheme_criterion: SchemeCriterion.find_by(id: 3338))
requirement_1_for_scheme_criterion_id_3339 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3339, scheme_criterion: SchemeCriterion.find_by(id: 3339))
requirement_2_for_scheme_criterion_id_3339 = Requirement.create!(name: "Executive Summary for On-Site Measurements of daylight levels.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3339, scheme_criterion: SchemeCriterion.find_by(id: 3339))
requirement_3_for_scheme_criterion_id_3339 = Requirement.create!(name: "Records of daylight lux levels.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3339, scheme_criterion: SchemeCriterion.find_by(id: 3339))
requirement_4_for_scheme_criterion_id_3339 = Requirement.create!(name: "Building layout and specifications for measured spaces.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3339, scheme_criterion: SchemeCriterion.find_by(id: 3339))
requirement_1_for_scheme_criterion_id_3340 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3340, scheme_criterion: SchemeCriterion.find_by(id: 3340))
requirement_2_for_scheme_criterion_id_3340 = Requirement.create!(name: "Executive Summary for On-Site Measurements of daylight levels.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3340, scheme_criterion: SchemeCriterion.find_by(id: 3340))
requirement_3_for_scheme_criterion_id_3340 = Requirement.create!(name: "Records of daylight lux levels.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3340, scheme_criterion: SchemeCriterion.find_by(id: 3340))
requirement_4_for_scheme_criterion_id_3340 = Requirement.create!(name: "Building layout and specifications for measured spaces.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3340, scheme_criterion: SchemeCriterion.find_by(id: 3340))
requirement_1_for_scheme_criterion_id_3341 = Requirement.create!(name: "Executive Summary, highlighting the approach to the criterion, measures implemented and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3341, scheme_criterion: SchemeCriterion.find_by(id: 3341))
requirement_2_for_scheme_criterion_id_3341 = Requirement.create!(name: "As-Built architectural drawings for the building")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3341, scheme_criterion: SchemeCriterion.find_by(id: 3341))
requirement_3_for_scheme_criterion_id_3341 = Requirement.create!(name: "As-Built MEP drawings related to the building systems including specifications and data sheets")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3341, scheme_criterion: SchemeCriterion.find_by(id: 3341))
requirement_4_for_scheme_criterion_id_3341 = Requirement.create!(name: "Energy meters and monitoring data.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3341, scheme_criterion: SchemeCriterion.find_by(id: 3341))
requirement_5_for_scheme_criterion_id_3341 = Requirement.create!(name: "GSAS Energia Suite™ and evidence of the relevant calculated and measured data.")
SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3341, scheme_criterion: SchemeCriterion.find_by(id: 3341))
requirement_1_for_scheme_criterion_id_3342 = Requirement.create!(name: "Executive Summary, highlighting the approach to the criterion, measures implemented and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3342, scheme_criterion: SchemeCriterion.find_by(id: 3342))
requirement_2_for_scheme_criterion_id_3342 = Requirement.create!(name: "As-Built architectural drawings for the building")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3342, scheme_criterion: SchemeCriterion.find_by(id: 3342))
requirement_3_for_scheme_criterion_id_3342 = Requirement.create!(name: "As-Built MEP drawings related to the building systems including specifications and data sheets")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3342, scheme_criterion: SchemeCriterion.find_by(id: 3342))
requirement_4_for_scheme_criterion_id_3342 = Requirement.create!(name: "Energy meters and monitoring data.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3342, scheme_criterion: SchemeCriterion.find_by(id: 3342))
requirement_5_for_scheme_criterion_id_3342 = Requirement.create!(name: "GSAS Energia Suite™ and evidence of the relevant calculated and measured data.")
SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3342, scheme_criterion: SchemeCriterion.find_by(id: 3342))
requirement_1_for_scheme_criterion_id_3343 = Requirement.create!(name: "Executive Summary highlighting the measures implemented in accordance with the Facility Management Plan and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3343, scheme_criterion: SchemeCriterion.find_by(id: 3343))
requirement_2_for_scheme_criterion_id_3343 = Requirement.create!(name: "Records for evidence towards facility management provisions.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3343, scheme_criterion: SchemeCriterion.find_by(id: 3343))
requirement_3_for_scheme_criterion_id_3343 = Requirement.create!(name: "Executive Summary for the Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3343, scheme_criterion: SchemeCriterion.find_by(id: 3343))
requirement_4_for_scheme_criterion_id_3343 = Requirement.create!(name: "Facility Management Plan")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3343, scheme_criterion: SchemeCriterion.find_by(id: 3343))
requirement_1_for_scheme_criterion_id_3344 = Requirement.create!(name: "Executive Summary highlighting the measures implemented in accordance with the Facility Management Plan and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3344, scheme_criterion: SchemeCriterion.find_by(id: 3344))
requirement_2_for_scheme_criterion_id_3344 = Requirement.create!(name: "Records for evidence towards facility management provisions.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3344, scheme_criterion: SchemeCriterion.find_by(id: 3344))
requirement_3_for_scheme_criterion_id_3344 = Requirement.create!(name: "Executive Summary for the Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3344, scheme_criterion: SchemeCriterion.find_by(id: 3344))
requirement_4_for_scheme_criterion_id_3344 = Requirement.create!(name: "Facility Management Plan")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3344, scheme_criterion: SchemeCriterion.find_by(id: 3344))
requirement_1_for_scheme_criterion_id_3345 = Requirement.create!(name: "Executive Summary highlighting the measures implemented in accordance with the Facility Management Plan and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3345, scheme_criterion: SchemeCriterion.find_by(id: 3345))
requirement_2_for_scheme_criterion_id_3345 = Requirement.create!(name: "Records for evidence towards facility management provisions.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3345, scheme_criterion: SchemeCriterion.find_by(id: 3345))
requirement_3_for_scheme_criterion_id_3345 = Requirement.create!(name: "Executive Summary for the Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3345, scheme_criterion: SchemeCriterion.find_by(id: 3345))
requirement_4_for_scheme_criterion_id_3345 = Requirement.create!(name: "Facility Management Plan")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3345, scheme_criterion: SchemeCriterion.find_by(id: 3345))
requirement_1_for_scheme_criterion_id_3346 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3346, scheme_criterion: SchemeCriterion.find_by(id: 3346))
requirement_2_for_scheme_criterion_id_3346 = Requirement.create!(name: "Executive Summary for On-Site Measurements of lighting levels including the trend logs and data analysis.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3346, scheme_criterion: SchemeCriterion.find_by(id: 3346))
requirement_3_for_scheme_criterion_id_3346 = Requirement.create!(name: "Lux levels prescribed by IESNA or equivalent international standards for predominantly occupied space.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3346, scheme_criterion: SchemeCriterion.find_by(id: 3346))
requirement_4_for_scheme_criterion_id_3346 = Requirement.create!(name: "Primary building layout drawings with specifications for critical spaces.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3346, scheme_criterion: SchemeCriterion.find_by(id: 3346))
requirement_5_for_scheme_criterion_id_3346 = Requirement.create!(name: "Lighting system and controls layout, luminaire specifications and operation schedule.")
SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3346, scheme_criterion: SchemeCriterion.find_by(id: 3346))
requirement_1_for_scheme_criterion_id_3347 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3347, scheme_criterion: SchemeCriterion.find_by(id: 3347))
requirement_2_for_scheme_criterion_id_3347 = Requirement.create!(name: "Executive Summary for On-Site Measurements of lighting levels including the trend logs and data analysis.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3347, scheme_criterion: SchemeCriterion.find_by(id: 3347))
requirement_3_for_scheme_criterion_id_3347 = Requirement.create!(name: "Lux levels prescribed by IESNA or equivalent international standards for predominantly occupied space.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3347, scheme_criterion: SchemeCriterion.find_by(id: 3347))
requirement_4_for_scheme_criterion_id_3347 = Requirement.create!(name: "Primary building layout drawings with specifications for critical spaces.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3347, scheme_criterion: SchemeCriterion.find_by(id: 3347))
requirement_5_for_scheme_criterion_id_3347 = Requirement.create!(name: "Lighting system and controls layout, luminaire specifications and operation schedule.")
SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3347, scheme_criterion: SchemeCriterion.find_by(id: 3347))
requirement_1_for_scheme_criterion_id_3348 = Requirement.create!(name: "Samples of initiatives materials.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3348, scheme_criterion: SchemeCriterion.find_by(id: 3348))
requirement_2_for_scheme_criterion_id_3348 = Requirement.create!(name: "Implementation report")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3348, scheme_criterion: SchemeCriterion.find_by(id: 3348))
requirement_3_for_scheme_criterion_id_3348 = Requirement.create!(name: "Photos and other evidence of implemented initiatives.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3348, scheme_criterion: SchemeCriterion.find_by(id: 3348))
requirement_4_for_scheme_criterion_id_3348 = Requirement.create!(name: "Sustainability Awareness Plan.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3348, scheme_criterion: SchemeCriterion.find_by(id: 3348))
requirement_1_for_scheme_criterion_id_3349 = Requirement.create!(name: "Samples of initiatives materials.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3349, scheme_criterion: SchemeCriterion.find_by(id: 3349))
requirement_2_for_scheme_criterion_id_3349 = Requirement.create!(name: "Implementation report")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3349, scheme_criterion: SchemeCriterion.find_by(id: 3349))
requirement_3_for_scheme_criterion_id_3349 = Requirement.create!(name: "Photos and other evidence of implemented initiatives.")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3349, scheme_criterion: SchemeCriterion.find_by(id: 3349))
requirement_4_for_scheme_criterion_id_3349 = Requirement.create!(name: "Sustainability Awareness Plan.")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3349, scheme_criterion: SchemeCriterion.find_by(id: 3349))
requirement_1_for_scheme_criterion_id_3350 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3350, scheme_criterion: SchemeCriterion.find_by(id: 3350))
requirement_2_for_scheme_criterion_id_3350 = Requirement.create!(name: "Executive Summary for On-Site Measurements of thermal comfort parameters including the trend logs and data analysis.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3350, scheme_criterion: SchemeCriterion.find_by(id: 3350))
requirement_1_for_scheme_criterion_id_3351 = Requirement.create!(name: "Executive Summary for Occupant Survey.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3351, scheme_criterion: SchemeCriterion.find_by(id: 3351))
requirement_2_for_scheme_criterion_id_3351 = Requirement.create!(name: "Executive Summary for On-Site Measurements of thermal comfort parameters including the trend logs and data analysis.")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3351, scheme_criterion: SchemeCriterion.find_by(id: 3351))
requirement_1_for_scheme_criterion_id_3352 = Requirement.create!(name: "Executive Summary highlighting the measures implemented in accordance with the Waste Management Plan and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3352, scheme_criterion: SchemeCriterion.find_by(id: 3352))
requirement_2_for_scheme_criterion_id_3352 = Requirement.create!(name: "Records for evidence towards waste management actions (Photos/videos, documents, etc.).")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3352, scheme_criterion: SchemeCriterion.find_by(id: 3352))
requirement_3_for_scheme_criterion_id_3352 = Requirement.create!(name: "On-site measurement records for waste diverted from landfill or incineration")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3352, scheme_criterion: SchemeCriterion.find_by(id: 3352))
requirement_4_for_scheme_criterion_id_3352 = Requirement.create!(name: "Waste Management Plan")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3352, scheme_criterion: SchemeCriterion.find_by(id: 3352))
requirement_1_for_scheme_criterion_id_3353 = Requirement.create!(name: "Executive Summary highlighting the measures implemented in accordance with the Waste Management Plan and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3353, scheme_criterion: SchemeCriterion.find_by(id: 3353))
requirement_2_for_scheme_criterion_id_3353 = Requirement.create!(name: "Records for evidence towards waste management actions (Photos/videos, documents, etc.).")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3353, scheme_criterion: SchemeCriterion.find_by(id: 3353))
requirement_3_for_scheme_criterion_id_3353 = Requirement.create!(name: "On-site measurement records for waste diverted from landfill or incineration")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3353, scheme_criterion: SchemeCriterion.find_by(id: 3353))
requirement_4_for_scheme_criterion_id_3353 = Requirement.create!(name: "Waste Management Plan")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3353, scheme_criterion: SchemeCriterion.find_by(id: 3353))
requirement_1_for_scheme_criterion_id_3354 = Requirement.create!(name: "Executive Summary, highlighting the approach to the criterion, measures implemented and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_2_for_scheme_criterion_id_3354 = Requirement.create!(name: "As-Built architectural drawings for the building;")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_3_for_scheme_criterion_id_3354 = Requirement.create!(name: "As-Built MEP drawings related to the building systems including specifications and data sheets;")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_4_for_scheme_criterion_id_3354 = Requirement.create!(name: "Water meters and monitoring data;")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_5_for_scheme_criterion_id_3354 = Requirement.create!(name: "Drawings and technical data on landscape and plant species;")
SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_6_for_scheme_criterion_id_3354 = Requirement.create!(name: "Drawings and specifications of water recycling and reuse systems;")
SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_7_for_scheme_criterion_id_3354 = Requirement.create!(name: "Reused water tests/analysis, if applicable, by an accredited laboratory and approvals by concerned authorities.")
SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_8_for_scheme_criterion_id_3354 = Requirement.create!(name: "GSAS Water Tool™ and evidence of the relevant calculated and measured data.")
SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3354, scheme_criterion: SchemeCriterion.find_by(id: 3354))
requirement_1_for_scheme_criterion_id_3355 = Requirement.create!(name: "Executive Summary, highlighting the approach to the criterion, measures implemented and describing the structure and details of the submissions.")
SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_2_for_scheme_criterion_id_3355 = Requirement.create!(name: "As-Built architectural drawings for the building;")
SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_3_for_scheme_criterion_id_3355 = Requirement.create!(name: "As-Built MEP drawings related to the building systems including specifications and data sheets;")
SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_4_for_scheme_criterion_id_3355 = Requirement.create!(name: "Water meters and monitoring data;")
SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_5_for_scheme_criterion_id_3355 = Requirement.create!(name: "Drawings and technical data on landscape and plant species;")
SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_6_for_scheme_criterion_id_3355 = Requirement.create!(name: "Drawings and specifications of water recycling and reuse systems;")
SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_7_for_scheme_criterion_id_3355 = Requirement.create!(name: "Reused water tests/analysis, if applicable, by an accredited laboratory and approvals by concerned authorities.")
SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
requirement_8_for_scheme_criterion_id_3355 = Requirement.create!(name: "GSAS Water Tool™ and evidence of the relevant calculated and measured data.")
SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3355, scheme_criterion: SchemeCriterion.find_by(id: 3355))
