# SchemeCategories display_weights
SchemeCategory.where(scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "FM").update_all(display_weight: 50)
SchemeCategory.where(scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "IE").update_all(display_weight: 30)
SchemeCategory.where(scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "WM").update_all(display_weight: 40)
SchemeCategory.where(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "E").update_all(display_weight: 10)
SchemeCategory.where(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "FM").update_all(display_weight: 50)
SchemeCategory.where(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "IE").update_all(display_weight: 30)
SchemeCategory.where(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "SA").update_all(display_weight: 60)
SchemeCategory.where(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "W").update_all(display_weight: 20)
SchemeCategory.where(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "WM").update_all(display_weight: 40)
SchemeCategory.where(scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "E").update_all(display_weight: 10)
SchemeCategory.where(scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "FM").update_all(display_weight: 50)
SchemeCategory.where(scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "SA").update_all(display_weight: 60)
SchemeCategory.where(scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), code: "W").update_all(display_weight: 20)

# SchemeCriterion labels
SchemeCriterion.where(name: 'Daylight & Views', scheme_category: SchemeCategory.find_by(code: "IE", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'Daylight', label_b: 'Views')
SchemeCriterion.where(name: 'Daylight & Views', scheme_category: SchemeCategory.find_by(code: "IE", scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'Daylight', label_b: 'Views')

SchemeCriterion.where(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated')
SchemeCriterion.where(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated')

SchemeCriterion.where(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated')
SchemeCriterion.where(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated')

# INCENTIVES
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: 'Sub-metering')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: 'Sub-metering')

SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: '2.50% Renewable Energy Supply')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: '2.50% Renewable Energy Supply')

SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: '100% Solar Hot Water Supply')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: '100% Solar Hot Water Supply')

SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 5.00, label: 'GSAS Accredited Energy Auditing Service Provider')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 5.00, label: 'GSAS Accredited Energy Auditing Service Provider')

SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: 'Sub-metering')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))).update_all(label_a: 'As Built', label_b: 'As Operated'), incentive_weight: 2.50, label: 'Sub-metering')

SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Waste Management", scheme_category: SchemeCategory.find_by(code: "WM", scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), incentive_weight: 5.00, label: 'GSAS Accredited Waste Management Service Provider')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Waste Management", scheme_category: SchemeCategory.find_by(code: "WM", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), incentive_weight: 5.00, label: 'GSAS Accredited Waste Management Service Provider')

SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Facility Management", scheme_category: SchemeCategory.find_by(code: "FM", scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), incentive_weight: 5.00, label: 'GSAS Accredited Facility Management Service Provider')
SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Facility Management", scheme_category: SchemeCategory.find_by(code: "FM", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), incentive_weight: 5.00, label: 'GSAS Accredited Facility Management Service Provider')

# PERFORMANCE LABEL
SchemeCriterionEpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Built', display_weight: 0, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionEpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Operated', display_weight: 1, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionEpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Built', display_weight: 0, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionEpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Energy', scheme_category: SchemeCategory.find_by(code: "E", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Operated', display_weight: 1, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionWpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Built', display_weight: 0, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionWpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Operated', display_weight: 1, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionWpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Built', display_weight: 0, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))
SchemeCriterionWpl.create!(scheme_criterion: SchemeCriterion.find_by(name: 'Water', scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false))), label: 'As Operated', display_weight: 1, levels: YAML.load("[0, 1, 2, 3]\n"), bands: YAML.load("['A*', 'A', 'B', 'C', 'D', 'E', 'F', 'G']\n"))