Owner.find_or_create_by!(name: 'Aspire Zone Foundation (AZF)', governmental: true)
Owner.find_or_create_by!(name: 'Barwa', private_owner: true)
Owner.find_or_create_by!(name: 'Hamad Medical Corporation (HMC)', governmental: true)
Owner.find_or_create_by!(name: 'Internal Security Force (Lekhwiya)', governmental: true)
Owner.find_or_create_by!(name: 'Katara Hospitality', private_owner: true)
Owner.find_or_create_by!(name: 'Milaha Maritime & Logistics', private_owner: true)
Owner.find_or_create_by!(name: 'Ministry of Commerce and Industry', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Communications and Information Technology', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Culture', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Defense', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Education and Higher Education', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Endowments and Islamic Affairs', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Environment and Climate Change', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Finance', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Interior', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Justice', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Labor', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Municipality', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Public Health', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Social Development and Family', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Sports and Youth', governmental: true)
Owner.find_or_create_by!(name: 'Ministry of Transport', governmental: true)
Owner.find_or_create_by!(name: 'New Port Project (NPP)', governmental: true)
Owner.find_or_create_by!(name: 'Primary Health Care Corporation (PHCC)', private_owner: true)
Owner.find_or_create_by!(name: 'Private Sector', private_owner: true)
Owner.find_or_create_by!(name: 'Public Works Authority (ASHGHAL)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar Company for Airport Operations & Management (MATAR)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar Economic Zone Company (MANATEQ)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar Energy (QE)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar Foundation (QF)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar General Electricity & Water Corporation (KAHRAMAA)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar Museums (QM)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar Rail (QR)', governmental: true)
Owner.find_or_create_by!(name: 'Qatar University (QU)', governmental: true)
Owner.find_or_create_by!(name: 'Qatari Diar', private_developer: true)
Owner.find_or_create_by!(name: 'QETAIFAN Projects', governmental: true)
Owner.find_or_create_by!(name: 'QTerminals', governmental: true)
Owner.find_or_create_by!(name: 'Supreme Committee for Delivery & Legacy (SC)', governmental: true)

puts "Owners are added successfully.........."
