# VITO users
User.create!(email: 'sas@vito.be', password: 'password', password_confirmation: 'password', role: :system_admin)
User.create!(email: 'karel.styns@vito.be', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'bart.dooms@vito.be', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'koen.dierckx@vito.be', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'bart.daniels@vito.be', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'kristof.dhalle@vito.be', password: 'password', password_confirmation: 'password', role: :user)

# GORD users
User.create!(email: 'alhorr@gord.qa', password: 'password', password_confirmation: 'password', role: :gord_top_manager)
User.create!(email: 'e.elsarrag@gord.qa', password: 'password', password_confirmation: 'password', role: :gord_manager)
User.create!(email: 'o.khidir@gord.qa', password: 'password', password_confirmation: 'password', role: :system_admin)
User.create!(email: 'm.manaman@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'm.zaki@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'm.alhumaiqani@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'e.eliskandarani@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'w.salah@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'a.zivkovic@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'm.katafygiotou@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'r.elhayek@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'm.chakravarthy@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 'r.dalistan@gord.qa', password: 'password', password_confirmation: 'password', role: :user)
User.create!(email: 's.alayoubi@gord.qa', password: 'password', password_confirmation: 'password', role: :user)

# DigitalNexa users
User.create!(email: 'amit@digitalnexa.com', password: 'password', password_confirmation: 'password', role: :user)

# Standard notification profiles
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('sas@vito.be'))
NotificationTypesUser.create!(notification_type_id: 2, user_id: User.find_by_email('sas@vito.be'))
NotificationTypesUser.create!(notification_type_id: 3, user_id: User.find_by_email('sas@vito.be'))
NotificationTypesUser.create!(notification_type_id: 7, user_id: User.find_by_email('sas@vito.be'))
NotificationTypesUser.create!(notification_type_id: 11, user_id: User.find_by_email('sas@vito.be'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('sas@vito.be'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('o.khidir@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 2, user_id: User.find_by_email('o.khidir@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 3, user_id: User.find_by_email('o.khidir@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 7, user_id: User.find_by_email('o.khidir@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 11, user_id: User.find_by_email('o.khidir@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('o.khidir@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('m.manaman@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('karel.styns@vito.be'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('bart.dooms@vito.be'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('koen.dierckx@vito.be'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('bart.daniels@vito.be'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('kristof.dhalle@vito.be'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('m.zaki@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('m.alhumaiqani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('e.eliskandarani@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('w.salah@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('a.zivkovic@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('m.katafygiotou@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('r.elhayek@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('m.chakravarthy@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('r.dalistan@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('s.alayoubi@gord.qa'))
NotificationTypesUser.create!(notification_type_id: 1, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 4, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 6, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 8, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 10, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 12, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 14, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 16, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 22, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 23, user_id: User.find_by_email('amit@digitalnexa.com'))
NotificationTypesUser.create!(notification_type_id: 25, user_id: User.find_by_email('amit@digitalnexa.com'))
