# System Admin
User.create!(
  email: "system_admin@gsb.qa",
  username: "system_admin",
  confirmed_at: DateTime.now,
  role: "system_admin",
  name: "System Admin",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "system_admin1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# GSB Trust Top Manager
User.create!(
  email: "gsb_trust_top_manager@gsb.qa",
  username: "gsb_trust_top_manager",
  confirmed_at: DateTime.now,
  role: "gsb_trust_top_manager",
  name: "GSB Trust Top Manager",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "gsb_trust_top_manager1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# GSB Trust Manager
User.create!(
  email: "gsb_trust_manager@gsb.qa",
  username: "gsb_trust_manager",
  confirmed_at: DateTime.now,
  role: "gsb_trust_manager",
  name: "GSB Trust Manager",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "gsb_trust_manager1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# GSB Trust Admin
User.create!(
  email: "gsb_trust_admin@gsb.qa",
  username: "gsb_trust_admin",
  confirmed_at: DateTime.now,
  role: "gsb_trust_admin",
  name: "GSB Trust Admin",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "gsb_trust_admin1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# Document Controller
User.create!(
  email: "document_controller@gsb.qa",
  username: "document_controller",
  confirmed_at: DateTime.now,
  role: "document_controller",
  name: "Document Controller",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "document_controller1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# Record Checker
User.create!(
  email: "record_checker@gsb.qa",
  username: "record_checker",
  confirmed_at: DateTime.now,
  role: "record_checker",
  name: "Record Checker",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "record_checker1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# Users Admin
User.create!(
  email: "users_admin@gsb.qa",
  username: "users_admin",
  confirmed_at: DateTime.now,
  role: "users_admin",
  name: "Users Admin",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "users_admin1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# Credentials Admin
User.create!(
  email: "credentials_admin@gsb.qa",
  username: "credentials_admin",
  confirmed_at: DateTime.now,
  role: "credentials_admin",
  name: "Credentials Admin",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "credentials_admin1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)

# Certification Manager
User.create!(
  email: "certification_manager@gsb.qa",
  username: "certification_manager",
  confirmed_at: DateTime.now,
  role: "certification_manager",
  name: "Certification Manager",
  gord_employee: true,
  organization_name: "GORD GSB",
  name_suffix: "Mr",
  last_name: "1",
  email_alternate: "certification_manager1@gsb.qa",
  country: "Qatar",
  city: "Al Daayen",
  mobile_area_code: "11111",
  mobile: "9874563210",
  active: true,
  organization_address: "Test",
  organization_country: "Qatar",
  organization_city: "Al Daayen",
  organization_website: "https://www.gsbgord.qa",
  organization_phone_area_code: "11111",
  approved_at: true,
  organization_email: "gsb_gord@gsb.qa",
  password: "aaaaaa",
  password_confirmation: "aaaaaa"
)
