source 'http://rubygems.org'

gem 'rails', '~> 5.2.0'

gem 'addressable'
gem 'bcrypt'
gem 'bootsnap'
gem 'bootstrap_form', '~> 2.7'
gem 'bundler'
gem 'cancancan'
gem 'carrierwave'
gem 'ckeditor'
gem 'effective_datatables', '< 4.0.0'
gem 'execjs'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'html2haml'
gem 'httparty'
gem 'jbuilder'
gem 'js-routes'
gem 'kaminari'
gem 'nokogiri'
gem 'pdf-core'
gem 'pg'
gem 'prawn'
gem 'prawn-table'
gem 'puma'
gem 'roo'
gem 'rubyzip'
gem 'sass-rails'
gem 'select2-rails', '< 4.0.0'
gem 'sprockets'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'uglifier'
gem 'warden'
gem 'warden-jwt_auth'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-npm'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-systemd'
end

source 'http://rails-assets.org' do
  gem 'rails-assets-animate.css'
  gem 'rails-assets-bootstrap', '~> 3.0'
  gem 'rails-assets-bootstrap-datepicker'
  gem 'rails-assets-bootstrap-timepicker'
  gem 'rails-assets-d3', '~> 4.13'
  gem 'rails-assets-d3-tip', '~> 0.7.1'
  gem 'rails-assets-dropzone'
  gem 'rails-assets-icheck'
  gem 'rails-assets-jquery'
  gem 'rails-assets-jquery-ujs'
  gem 'rails-assets-leaflet'
  gem 'rails-assets-leaflet-draw'
  gem 'rails-assets-metisMenu'
  gem 'rails-assets-pace'
  gem 'rails-assets-proj4'
  gem 'rails-assets-slimScroll'
  gem 'rails-assets-three.js'
  gem 'rails-assets-toastr'
  gem 'rails-assets-voidberg--html5sortable'
end
