class AddCm21Issue3Requirements < ActiveRecord::Migration[4.2]
  def change
    requirement_1_for_scheme_criterion_id_3298 = Requirement.create!(name: "0. Domestic Water Management Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_2_for_scheme_criterion_id_3298 = Requirement.create!(name: "I. Domestic Water Management Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_3_for_scheme_criterion_id_3298 = Requirement.create!(name: "I.a. Documents outlining the water use activities and control measures")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_4_for_scheme_criterion_id_3298 = Requirement.create!(name: "I.b. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_5_for_scheme_criterion_id_3298 = Requirement.create!(name: "I.c. Activities schedule and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_6_for_scheme_criterion_id_3298 = Requirement.create!(name: "I.d. Any other supporting documents or evidences that demonstrate the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_7_for_scheme_criterion_id_3298 = Requirement.create!(name: "II. Water Management Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_8_for_scheme_criterion_id_3298 = Requirement.create!(name: "II.a. Facilities and fixtures lists, data sheets and specifications")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_9_for_scheme_criterion_id_3298 = Requirement.create!(name: "II.b. Domestic Water consumption data")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_10_for_scheme_criterion_id_3298 = Requirement.create!(name: "II.c. Monitoring devices, protocols and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_11_for_scheme_criterion_id_3298 = Requirement.create!(name: "III. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_11_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_12_for_scheme_criterion_id_3298 = Requirement.create!(name: "IV. Supporting documents and evidences of additional efforts on sub-metering, if continuous monitoring is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_12_for_scheme_criterion_id_3298, scheme_criterion: SchemeCriterion.find_by(id: 3298))
    requirement_1_for_scheme_criterion_id_3309 = Requirement.create!(name: "0. Non-Domestic Water Management Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_2_for_scheme_criterion_id_3309 = Requirement.create!(name: "I. Non-Domestic Water Management Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_3_for_scheme_criterion_id_3309 = Requirement.create!(name: "I.a. Documents outlining the water use activities and control measures")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_4_for_scheme_criterion_id_3309 = Requirement.create!(name: "I.b. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_5_for_scheme_criterion_id_3309 = Requirement.create!(name: "I.c. Activities schedule and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_6_for_scheme_criterion_id_3309 = Requirement.create!(name: "I.d. Any other supporting documents or evidences that demonstrate the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_7_for_scheme_criterion_id_3309 = Requirement.create!(name: "II. Water Management Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_8_for_scheme_criterion_id_3309 = Requirement.create!(name: "II.a. Facilities and fixtures lists, data sheets and specifications")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_9_for_scheme_criterion_id_3309 = Requirement.create!(name: "II.b. Domestic Water consumption data")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_10_for_scheme_criterion_id_3309 = Requirement.create!(name: "II.c. Monitoring devices, protocols and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_11_for_scheme_criterion_id_3309 = Requirement.create!(name: "III. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_11_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_12_for_scheme_criterion_id_3309 = Requirement.create!(name: "IV. Supporting documents and evidences of additional efforts on sub-metering, if continuous monitoring is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_12_for_scheme_criterion_id_3309, scheme_criterion: SchemeCriterion.find_by(id: 3309))
    requirement_1_for_scheme_criterion_id_3318 = Requirement.create!(name: "Traffic & Transportation Management Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_2_for_scheme_criterion_id_3318 = Requirement.create!(name: "Traffic & Transportation Management Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_3_for_scheme_criterion_id_3318 = Requirement.create!(name: "Site map with clear directions indicating the alternative access points, road layouts, construction routes and parking")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_4_for_scheme_criterion_id_3318 = Requirement.create!(name: "Adjacent roads’ map including any road closures and traffic diversions")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_5_for_scheme_criterion_id_3318 = Requirement.create!(name: "Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_6_for_scheme_criterion_id_3318 = Requirement.create!(name: "Schedules of activities and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_7_for_scheme_criterion_id_3318 = Requirement.create!(name: "Local Authorities Permits for road closures and diversions")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_8_for_scheme_criterion_id_3318 = Requirement.create!(name: "Any other supporting document or evidence that demonstrates the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3318, scheme_criterion: SchemeCriterion.find_by(id: 3318))
    requirement_1_for_scheme_criterion_id_3315 = Requirement.create!(name: "Sewer and Waterway Contamination Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3315, scheme_criterion: SchemeCriterion.find_by(id: 3315))
    requirement_2_for_scheme_criterion_id_3315 = Requirement.create!(name: "Sewer and Waterway Contamination Control Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3315, scheme_criterion: SchemeCriterion.find_by(id: 3315))
    requirement_3_for_scheme_criterion_id_3315 = Requirement.create!(name: "Drawings for storm water and sanitary drainage systems")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3315, scheme_criterion: SchemeCriterion.find_by(id: 3315))
    requirement_4_for_scheme_criterion_id_3315 = Requirement.create!(name: "Drawings for storm water and sanitary tank filtration systems")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3315, scheme_criterion: SchemeCriterion.find_by(id: 3315))
    requirement_5_for_scheme_criterion_id_3315 = Requirement.create!(name: "Physical and chemical tests conducted on the waste water, discharged into the public networks")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3315, scheme_criterion: SchemeCriterion.find_by(id: 3315))
    requirement_1_for_scheme_criterion_id_3313 = Requirement.create!(name: "Reclamation and Dredging Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3313, scheme_criterion: SchemeCriterion.find_by(id: 3313))
    requirement_2_for_scheme_criterion_id_3313 = Requirement.create!(name: "Reclamation and Dredging Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3313, scheme_criterion: SchemeCriterion.find_by(id: 3313))
    requirement_3_for_scheme_criterion_id_3313 = Requirement.create!(name: "Documents outlining activities and schedules")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3313, scheme_criterion: SchemeCriterion.find_by(id: 3313))
    requirement_4_for_scheme_criterion_id_3313 = Requirement.create!(name: "Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3313, scheme_criterion: SchemeCriterion.find_by(id: 3313))
    requirement_5_for_scheme_criterion_id_3313 = Requirement.create!(name: "Monitoring protocols and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3313, scheme_criterion: SchemeCriterion.find_by(id: 3313))
    requirement_6_for_scheme_criterion_id_3313 = Requirement.create!(name: "Any other supporting document or evidence that demonstrates the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3313, scheme_criterion: SchemeCriterion.find_by(id: 3313))
    requirement_1_for_scheme_criterion_id_3312 = Requirement.create!(name: "Archeological Site Protection Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_2_for_scheme_criterion_id_3312 = Requirement.create!(name: "Archeological Site Protection Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_3_for_scheme_criterion_id_3312 = Requirement.create!(name: "Archeological survey/Archeological Impact Assessment, if applicable")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_4_for_scheme_criterion_id_3312 = Requirement.create!(name: "Letter of no objection from local and government authorities prior to any work commencing on site (if applicable)")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_5_for_scheme_criterion_id_3312 = Requirement.create!(name: "Documents outlining all important measures to protect the heritage sites from the effects of construction activities")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_6_for_scheme_criterion_id_3312 = Requirement.create!(name: "Drawings of the areas that are to be protected")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_7_for_scheme_criterion_id_3312 = Requirement.create!(name: "An archaeological watching brief, in-case archaeological discoveries are made")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_8_for_scheme_criterion_id_3312 = Requirement.create!(name: "Photographic evidences showing artifacts found, if applicable")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_9_for_scheme_criterion_id_3312 = Requirement.create!(name: "Any other supporting document deemed necessary")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3312, scheme_criterion: SchemeCriterion.find_by(id: 3312))
    requirement_1_for_scheme_criterion_id_3304 = Requirement.create!(name: "0. Land Preservation Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_2_for_scheme_criterion_id_3304 = Requirement.create!(name: "I. Land Preservation Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_3_for_scheme_criterion_id_3304 = Requirement.create!(name: "I.a. Site Assessment Report")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_4_for_scheme_criterion_id_3304 = Requirement.create!(name: "I.b. Soil Erosion Plan (if applicable)")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_5_for_scheme_criterion_id_3304 = Requirement.create!(name: "I.c. Site plan identifying areas of varying degrees of soil quality, soil disturbance, and contaminated land for pre- and post- development")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_6_for_scheme_criterion_id_3304 = Requirement.create!(name: "I.d. Site plan identifying areas to be conserved, restored, or enhanced")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_7_for_scheme_criterion_id_3304 = Requirement.create!(name: "I.e. Specifications that illustrate how site remediation, conservation, and restoration outlined in the Site Assessment Report will be implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_8_for_scheme_criterion_id_3304 = Requirement.create!(name: "I.f. Any other drawings that meet the specific requirements of the Site Assessment Report")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_9_for_scheme_criterion_id_3304 = Requirement.create!(name: "II. Land Preservation Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_10_for_scheme_criterion_id_3304 = Requirement.create!(name: "II.a. Calculator supporting documents similar to Section I.")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3304, scheme_criterion: SchemeCriterion.find_by(id: 3304))
    requirement_1_for_scheme_criterion_id_3303 = Requirement.create!(name: "Habitat Preservation Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_2_for_scheme_criterion_id_3303 = Requirement.create!(name: "Habitat Preservation Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_3_for_scheme_criterion_id_3303 = Requirement.create!(name: "Diagrams or drawings that identify all habitats in the construction site")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_4_for_scheme_criterion_id_3303 = Requirement.create!(name: "List of plant and animal species")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_5_for_scheme_criterion_id_3303 = Requirement.create!(name: "Site ecological value protection strategy report which contains  strategies for preserving ecosystem interaction within the site and adjacent areas")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_6_for_scheme_criterion_id_3303 = Requirement.create!(name: "Photographic evidences confirming planting in accordance with the design stage plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_7_for_scheme_criterion_id_3303 = Requirement.create!(name: "Tree Relocation/Cutting Permit, if applicable")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_8_for_scheme_criterion_id_3303 = Requirement.create!(name: "Tree Protection Plan including replanting strategies and specific method statement for tree preservation and transplantation")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_9_for_scheme_criterion_id_3303 = Requirement.create!(name: "Drawings showing the existing and new tree locations and numbers")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_10_for_scheme_criterion_id_3303 = Requirement.create!(name: "Evidences demonstrating unavailability of vegetation or endangered habitat (if applicable)")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3303, scheme_criterion: SchemeCriterion.find_by(id: 3303))
    requirement_1_for_scheme_criterion_id_3299 = Requirement.create!(name: "0. Dust Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_2_for_scheme_criterion_id_3299 = Requirement.create!(name: "I. Dust Monitoring and Control Report, demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_3_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.a. Dust Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_4_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.b. Documents outlining methods of dust mitigation on- site")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_5_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.c. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_6_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.d. Checklist and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_7_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.e. Activities schedules and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_8_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.f. Specification, measures and any other supporting documents")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_9_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.g. Drawings showing the location of on-site measurement points and adjacent receptors")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_10_for_scheme_criterion_id_3299 = Requirement.create!(name: "I.h. Any other supporting document or evidence that demonstrate the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_11_for_scheme_criterion_id_3299 = Requirement.create!(name: "II. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_11_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_12_for_scheme_criterion_id_3299 = Requirement.create!(name: "III. Documents and evidence if continouos monitoring is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_12_for_scheme_criterion_id_3299, scheme_criterion: SchemeCriterion.find_by(id: 3299))
    requirement_1_for_scheme_criterion_id_3308 = Requirement.create!(name: "0. Noise and Vibration Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_2_for_scheme_criterion_id_3308 = Requirement.create!(name: "I. Noise and Vibration Control Report, demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_3_for_scheme_criterion_id_3308 = Requirement.create!(name: "I.a. Documents outlining methods of noise mitigation in the site")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_4_for_scheme_criterion_id_3308 = Requirement.create!(name: "I.b. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_5_for_scheme_criterion_id_3308 = Requirement.create!(name: "I.c. Checklist and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_6_for_scheme_criterion_id_3308 = Requirement.create!(name: "I.d. Activities schedules and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_7_for_scheme_criterion_id_3308 = Requirement.create!(name: "I.e. Any other supporting document or evidence that demonstrates the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_8_for_scheme_criterion_id_3308 = Requirement.create!(name: "II. Noise Monitoring Report and Noise Control Calculator including on-site measurements data pertaining to noise from equipment and plants as well as noise affecting the neighborhood")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_9_for_scheme_criterion_id_3308 = Requirement.create!(name: "II.a. Drawings showing the location of on-site measurement points and adjacent receptors")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_10_for_scheme_criterion_id_3308 = Requirement.create!(name: "II.b. Specification, measures and any other supporting documents")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_11_for_scheme_criterion_id_3308 = Requirement.create!(name: "II.c. Photographs and videos of the monitoring")
    SchemeCriteriaRequirement.create!(requirement: requirement_11_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_12_for_scheme_criterion_id_3308 = Requirement.create!(name: "II.d. Any other supporting document or evidence that demonstrates the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_12_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_13_for_scheme_criterion_id_3308 = Requirement.create!(name: "III. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_13_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_14_for_scheme_criterion_id_3308 = Requirement.create!(name: "IV. Documents and evidence demonstrating the main equipment and plants don't exceed the allowable noise levels")
    SchemeCriteriaRequirement.create!(requirement: requirement_14_for_scheme_criterion_id_3308, scheme_criterion: SchemeCriterion.find_by(id: 3308))
    requirement_1_for_scheme_criterion_id_3319 = Requirement.create!(name: "0. Waste Management Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_2_for_scheme_criterion_id_3319 = Requirement.create!(name: "I. Waste Management Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_3_for_scheme_criterion_id_3319 = Requirement.create!(name: "I.a. Documents and drawings outlining waste prevention and reduction methods, including collection, segregation, storage, disposal of waste")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_4_for_scheme_criterion_id_3319 = Requirement.create!(name: "I.b. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_5_for_scheme_criterion_id_3319 = Requirement.create!(name: "I.c. Checklist and inspection reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_6_for_scheme_criterion_id_3319 = Requirement.create!(name: "I.d. Documents outlining treatment of hazardous waste, if applicable")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_7_for_scheme_criterion_id_3319 = Requirement.create!(name: "I.e. Agreement with third party and license")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_8_for_scheme_criterion_id_3319 = Requirement.create!(name: "I.f. Documents demonstrating waste collection and disposal such as logs and Waste Transfer Notes")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_9_for_scheme_criterion_id_3319 = Requirement.create!(name: "II. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3319, scheme_criterion: SchemeCriterion.find_by(id: 3319))
    requirement_1_for_scheme_criterion_id_3320 = Requirement.create!(name: "Welfare Facilities Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3320, scheme_criterion: SchemeCriterion.find_by(id: 3320))
    requirement_2_for_scheme_criterion_id_3320 = Requirement.create!(name: "Welfare Facilities Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3320, scheme_criterion: SchemeCriterion.find_by(id: 3320))
    requirement_3_for_scheme_criterion_id_3320 = Requirement.create!(name: "Filled-in survey questionnaires of both workers and officers")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3320, scheme_criterion: SchemeCriterion.find_by(id: 3320))
    requirement_4_for_scheme_criterion_id_3320 = Requirement.create!(name: "Documents and evidences of the survey")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3320, scheme_criterion: SchemeCriterion.find_by(id: 3320))
    requirement_5_for_scheme_criterion_id_3320 = Requirement.create!(name: "Justified calculations of satisfaction level")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3320, scheme_criterion: SchemeCriterion.find_by(id: 3320))
    requirement_1_for_scheme_criterion_id_3307 = Requirement.create!(name: "Case A - Inheritance. Evidence of GSAS Design & Build awarded score")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_2_for_scheme_criterion_id_3307 = Requirement.create!(name: "Case B - No Inheritance")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_3_for_scheme_criterion_id_3307 = Requirement.create!(name: "B.1. Materials Reuse Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_4_for_scheme_criterion_id_3307 = Requirement.create!(name: "B.2. Documents outlining the materials reuse activities and locations")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_5_for_scheme_criterion_id_3307 = Requirement.create!(name: "B.3. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_6_for_scheme_criterion_id_3307 = Requirement.create!(name: "B.4. Materials list, BOQ, cost sheets and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_7_for_scheme_criterion_id_3307 = Requirement.create!(name: "B.5. Activities schedule and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_8_for_scheme_criterion_id_3307 = Requirement.create!(name: "B.6.Any other supporting documents or evidences that demonstrate the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3307, scheme_criterion: SchemeCriterion.find_by(id: 3307))
    requirement_1_for_scheme_criterion_id_3300 = Requirement.create!(name: "0. Energy Management Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_2_for_scheme_criterion_id_3300 = Requirement.create!(name: "I. Energy Management Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_3_for_scheme_criterion_id_3300 = Requirement.create!(name: "I.a. As-built drawings for all offices, accommodations, canteen building as well as temporary office/accommodation structures attached to site")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_4_for_scheme_criterion_id_3300 = Requirement.create!(name: "I.b. Relevant mechanical, electrical, and plumbing (MEP); drawings and equipment specifications or data sheets")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_5_for_scheme_criterion_id_3300 = Requirement.create!(name: "I.c. Energy monitoring data")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_6_for_scheme_criterion_id_3300 = Requirement.create!(name: "I.d. Supporting documents for installed building materials and systems")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_7_for_scheme_criterion_id_3300 = Requirement.create!(name: "II. Energy Performance Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_8_for_scheme_criterion_id_3300 = Requirement.create!(name: "II.a. Calculator supporting documents similar to Section I")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_9_for_scheme_criterion_id_3300 = Requirement.create!(name: "III. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_10_for_scheme_criterion_id_3300 = Requirement.create!(name: "IV. Supporting documents and evidences of additional efforts on sub-metering, if continuous monitoring is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_10_for_scheme_criterion_id_3300, scheme_criterion: SchemeCriterion.find_by(id: 3300))
    requirement_1_for_scheme_criterion_id_3311 = Requirement.create!(name: "0. Energy Management and CO2 Emissions Reduction Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_2_for_scheme_criterion_id_3311 = Requirement.create!(name: "I. Energy Management and CO2 Emissions Reduction Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_3_for_scheme_criterion_id_3311 = Requirement.create!(name: "I.a. Relevant mechanical, electrical, and plumbing (MEP) equipment specifications or data sheets")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_4_for_scheme_criterion_id_3311 = Requirement.create!(name: "I.b. Energy monitoring data")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_5_for_scheme_criterion_id_3311 = Requirement.create!(name: "I.c. Supporting documents (e.g. name plate specifications, emission factors) for installed equipment and systems")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_6_for_scheme_criterion_id_3311 = Requirement.create!(name: "II. Energy Performance Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_7_for_scheme_criterion_id_3311 = Requirement.create!(name: "II.a. Calculator supporting documents similar to Section I")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_8_for_scheme_criterion_id_3311 = Requirement.create!(name: "III. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_9_for_scheme_criterion_id_3311 = Requirement.create!(name: "IV. Supporting documents and evidences of additional efforts on sub-metering, if continuous monitoring is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3311, scheme_criterion: SchemeCriterion.find_by(id: 3311))
    requirement_1_for_scheme_criterion_id_3316 = Requirement.create!(name: "Information Dissemination and Complaints Handling Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_2_for_scheme_criterion_id_3316 = Requirement.create!(name: "Information Dissemination and Complaints Handling Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_3_for_scheme_criterion_id_3316 = Requirement.create!(name: "Letter of no objection from local and government authorities prior to any work commencing on site")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_4_for_scheme_criterion_id_3316 = Requirement.create!(name: "Information package shared with community")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_5_for_scheme_criterion_id_3316 = Requirement.create!(name: "Documents outlining how complaints will be handled properly")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_6_for_scheme_criterion_id_3316 = Requirement.create!(name: "Communications protocol to liaise with the local communities")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_7_for_scheme_criterion_id_3316 = Requirement.create!(name: "Feedback forms and action plans")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3316, scheme_criterion: SchemeCriterion.find_by(id: 3316))
    requirement_1_for_scheme_criterion_id_3301 = Requirement.create!(name: "Erosion & Sediment Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3301, scheme_criterion: SchemeCriterion.find_by(id: 3301))
    requirement_2_for_scheme_criterion_id_3301 = Requirement.create!(name: "Erosion & Sediment Control Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3301, scheme_criterion: SchemeCriterion.find_by(id: 3301))
    requirement_3_for_scheme_criterion_id_3301 = Requirement.create!(name: "Site topographic map including soil survey information")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3301, scheme_criterion: SchemeCriterion.find_by(id: 3301))
    requirement_4_for_scheme_criterion_id_3301 = Requirement.create!(name: "Site development plan and project/construction schedule")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3301, scheme_criterion: SchemeCriterion.find_by(id: 3301))
    requirement_5_for_scheme_criterion_id_3301 = Requirement.create!(name: "Maintenance/monitoring plan of soil erosion & sediment control measures")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3301, scheme_criterion: SchemeCriterion.find_by(id: 3301))
    requirement_6_for_scheme_criterion_id_3301 = Requirement.create!(name: "Any other document deemed necessary for the support of effective control plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3301, scheme_criterion: SchemeCriterion.find_by(id: 3301))
    requirement_1_for_scheme_criterion_id_3317 = Requirement.create!(name: "Soil and Earthworks Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3317, scheme_criterion: SchemeCriterion.find_by(id: 3317))
    requirement_2_for_scheme_criterion_id_3317 = Requirement.create!(name: "Soil and Earthworks Control Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3317, scheme_criterion: SchemeCriterion.find_by(id: 3317))
    requirement_3_for_scheme_criterion_id_3317 = Requirement.create!(name: "Environmental Impacts Assessment (EIA) Report")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3317, scheme_criterion: SchemeCriterion.find_by(id: 3317))
    requirement_4_for_scheme_criterion_id_3317 = Requirement.create!(name: "Geotechnical investigation report")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3317, scheme_criterion: SchemeCriterion.find_by(id: 3317))
    requirement_5_for_scheme_criterion_id_3317 = Requirement.create!(name: "Contaminated site assessment report")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3317, scheme_criterion: SchemeCriterion.find_by(id: 3317))
    requirement_6_for_scheme_criterion_id_3317 = Requirement.create!(name: "Any other document deemed necessary for the support of effective control plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3317, scheme_criterion: SchemeCriterion.find_by(id: 3317))
    requirement_1_for_scheme_criterion_id_3305 = Requirement.create!(name: "Light Pollution and Visual Impact Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_2_for_scheme_criterion_id_3305 = Requirement.create!(name: "Light Pollution and Visual Impact Control Report demonstrating hoe the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_3_for_scheme_criterion_id_3305 = Requirement.create!(name: "Documents outlining methods of light mitigation in the site")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_4_for_scheme_criterion_id_3305 = Requirement.create!(name: "Documents outlining methods of mitigating potential visual impacts in the site")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_5_for_scheme_criterion_id_3305 = Requirement.create!(name: "Specification, measures and any other supporting documents")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_6_for_scheme_criterion_id_3305 = Requirement.create!(name: "Relevant external lighting drawings (plans and elevations)")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_7_for_scheme_criterion_id_3305 = Requirement.create!(name: "Relevant lighting manufacturers’ datasheets (including photometric data for individual lighting fixtures)")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3305, scheme_criterion: SchemeCriterion.find_by(id: 3305))
    requirement_1_for_scheme_criterion_id_3297 = Requirement.create!(name: "0. Construction Health & Safety Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_2_for_scheme_criterion_id_3297 = Requirement.create!(name: "I. Construction Health & Safety Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_3_for_scheme_criterion_id_3297 = Requirement.create!(name: "I.a. Documents outlining the management and protocols for health and safety strategies associated with the construction process")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_4_for_scheme_criterion_id_3297 = Requirement.create!(name: "I.b. Site plan identifying assembly point, emergency exits, staircases and provision of fire extinguishers, fire alarms")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_5_for_scheme_criterion_id_3297 = Requirement.create!(name: "I.c. Health & Safety reports, incidents log, checklists and inspection reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_6_for_scheme_criterion_id_3297 = Requirement.create!(name: "I.d. Evidences from construction site such as photos and records")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_7_for_scheme_criterion_id_3297 = Requirement.create!(name: "II. Relevant records for training and awareness generation")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3297, scheme_criterion: SchemeCriterion.find_by(id: 3297))
    requirement_1_for_scheme_criterion_id_3314 = Requirement.create!(name: "Case A - Inheritance. Evidence of GSAS Design & Build awarded score")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_2_for_scheme_criterion_id_3314 = Requirement.create!(name: "Case B - No Inheritance")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_3_for_scheme_criterion_id_3314 = Requirement.create!(name: "B.1. Recycled Materials Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_4_for_scheme_criterion_id_3314 = Requirement.create!(name: "B.2.Documents outlining the materials recycling activities and locations, as well as the use of materials with recycled content")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_5_for_scheme_criterion_id_3314 = Requirement.create!(name: "B.3. Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_6_for_scheme_criterion_id_3314 = Requirement.create!(name: "B.4. Materials list, BOQ, cost sheets and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_7_for_scheme_criterion_id_3314 = Requirement.create!(name: "B.5. Activities schedule and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_8_for_scheme_criterion_id_3314 = Requirement.create!(name: "B.6.Any other supporting documents or evidences that demonstrate the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3314, scheme_criterion: SchemeCriterion.find_by(id: 3314))
    requirement_1_for_scheme_criterion_id_3302 = Requirement.create!(name: "Groundwater and Dewatering Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_2_for_scheme_criterion_id_3302 = Requirement.create!(name: "Groundwater and Dewatering Control Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_3_for_scheme_criterion_id_3302 = Requirement.create!(name: "Evidences for the compliance of the provisions of the discharge permit")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_4_for_scheme_criterion_id_3302 = Requirement.create!(name: "Site map demonstrating location of discharge facility and area intended to receive the discharged water and route")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_5_for_scheme_criterion_id_3302 = Requirement.create!(name: "Site plan indicating dewatering network set-up")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_6_for_scheme_criterion_id_3302 = Requirement.create!(name: "Alternative options or locations for discharge, if applicable")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_7_for_scheme_criterion_id_3302 = Requirement.create!(name: "Groundwater investigation report")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_8_for_scheme_criterion_id_3302 = Requirement.create!(name: "Monitoring plan which includes reported dewatering problems and accidents")
    SchemeCriteriaRequirement.create!(requirement: requirement_8_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_9_for_scheme_criterion_id_3302 = Requirement.create!(name: "Laboratory analysis report for the quality of discharged waste water")
    SchemeCriteriaRequirement.create!(requirement: requirement_9_for_scheme_criterion_id_3302, scheme_criterion: SchemeCriterion.find_by(id: 3302))
    requirement_1_for_scheme_criterion_id_3310 = Requirement.create!(name: "Odor and VOC Emissions Control Plan")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3310, scheme_criterion: SchemeCriterion.find_by(id: 3310))
    requirement_2_for_scheme_criterion_id_3310 = Requirement.create!(name: "Odor and VOC Emissions Control Report demonstrating how the Plan is implemented")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3310, scheme_criterion: SchemeCriterion.find_by(id: 3310))
    requirement_3_for_scheme_criterion_id_3310 = Requirement.create!(name: "Drawings showing the location of septic tanks or sewage networks")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3310, scheme_criterion: SchemeCriterion.find_by(id: 3310))
    requirement_4_for_scheme_criterion_id_3310 = Requirement.create!(name: "Documents outlining methods of odor mitigation in the site, including proper waste management strategies")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3310, scheme_criterion: SchemeCriterion.find_by(id: 3310))
    requirement_5_for_scheme_criterion_id_3310 = Requirement.create!(name: "full list of volatile fuels and chemicals stored on site, indicating volumes, locations and Material Safety Data Sheets (MSDS)")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3310, scheme_criterion: SchemeCriterion.find_by(id: 3310))
    requirement_6_for_scheme_criterion_id_3310 = Requirement.create!(name: "Site plan identifying the proper on-site storage of volatile fuels and chemicals")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3310, scheme_criterion: SchemeCriterion.find_by(id: 3310))
    requirement_1_for_scheme_criterion_id_3321 = Requirement.create!(name: "Evidences for GSAS Design & Build certification of the workers’ accommodation")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3321, scheme_criterion: SchemeCriterion.find_by(id: 3321))
    requirement_1_for_scheme_criterion_id_3306 = Requirement.create!(name: "Materials Recovery Calculator")
    SchemeCriteriaRequirement.create!(requirement: requirement_1_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
    requirement_2_for_scheme_criterion_id_3306 = Requirement.create!(name: "Documents outlining the procedures of handling, collection, storage, and transfer of waste materials")
    SchemeCriteriaRequirement.create!(requirement: requirement_2_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
    requirement_3_for_scheme_criterion_id_3306 = Requirement.create!(name: "Waste tracking system using a Waste Transfer Note (WTN) or similar documentation showing details of recovered materials")
    SchemeCriteriaRequirement.create!(requirement: requirement_3_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
    requirement_4_for_scheme_criterion_id_3306 = Requirement.create!(name: "Photographs and videos")
    SchemeCriteriaRequirement.create!(requirement: requirement_4_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
    requirement_5_for_scheme_criterion_id_3306 = Requirement.create!(name: "Materials list, BOQ, cost sheets and audit reports")
    SchemeCriteriaRequirement.create!(requirement: requirement_5_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
    requirement_6_for_scheme_criterion_id_3306 = Requirement.create!(name: "Activities schedule and location maps")
    SchemeCriteriaRequirement.create!(requirement: requirement_6_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
    requirement_7_for_scheme_criterion_id_3306 = Requirement.create!(name: "Any other supporting documents or evidences that demonstrate the compliance")
    SchemeCriteriaRequirement.create!(requirement: requirement_7_for_scheme_criterion_id_3306, scheme_criterion: SchemeCriterion.find_by(id: 3306))
  end
end
