class AddNewDevelopmentTypesToOperations2019 < ActiveRecord::Migration[5.2]
  def change
    # Rename the existing single use development type
    single_use = DevelopmentType.find_by(name: "Single use operations", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019"))
    single_use.update_column(:name, 'Single Use')

    # Add 2 new development types
    DevelopmentType.create!(display_weight: 20, certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019"), mixable: false, name: 'Mixed Use')
    DevelopmentType.create!(display_weight: 30, certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019"), mixable: false, name: 'Single Zone (Interiors)')

    # Link all Operations 2019 schemes to the new development types
    DevelopmentTypeScheme.create!(scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), development_type: DevelopmentType.find_by(name: "Mixed Use", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019")))
    DevelopmentTypeScheme.create!(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), development_type: DevelopmentType.find_by(name: "Mixed Use", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019")))
    DevelopmentTypeScheme.create!(scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), development_type: DevelopmentType.find_by(name: "Mixed Use", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019")))
    DevelopmentTypeScheme.create!(scheme: Scheme.find_by(name: "Healthy Building Label Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), development_type: DevelopmentType.find_by(name: "Single Zone (Interiors)", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019")))
    DevelopmentTypeScheme.create!(scheme: Scheme.find_by(name: "Premium Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), development_type: DevelopmentType.find_by(name: "Single Zone (Interiors)", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019")))
    DevelopmentTypeScheme.create!(scheme: Scheme.find_by(name: "Standard Scheme", gsas_document: "GSAS Operations_Assessment & Guidelines_2019_04.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:operations_type], renovation:false), development_type: DevelopmentType.find_by(name: "Single Zone (Interiors)", certificate: Certificate.find_by(certificate_type: Certificate.certificate_types[:operations_type], assessment_stage: Certificate.assessment_stages[:operations_stage], gsas_version: "2019")))
  end
end
