class AddIncentivesForCm2019Stages2and3 < ActiveRecord::Migration[5.2]
  def change
    # Add incentive weights
    # E.1
    SchemeCriterion.where(name: "Energy Use - Temporary Buildings", number: 1, scheme_category: SchemeCategory.where(code: "E", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 1.5, incentive_weight_1_a: 1.5, incentive_weight_2_a: 1.5, incentive_weight_3_a: 1.5)
    # E.2
    SchemeCriterion.where(name: "Energy Use – Plant & Equipment", number: 2, scheme_category: SchemeCategory.where(code: "E", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 1.5, incentive_weight_1_a: 1.5, incentive_weight_2_a: 1.5, incentive_weight_3_a: 1.5)
    # W.1
    SchemeCriterion.where(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.where(code: "W", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 1.0, incentive_weight_1_a: 1.0, incentive_weight_2_a: 1.0, incentive_weight_3_a: 1.0)
    # W.2
    SchemeCriterion.where(name: "Non-Domestic Water Use", number: 2, scheme_category: SchemeCategory.where(code: "W", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 1.0, incentive_weight_1_a: 1.0, incentive_weight_2_a: 1.0, incentive_weight_3_a: 1.0)
    # OE.1
    SchemeCriterion.where(name: "Dust Control", number: 1, scheme_category: SchemeCategory.where(code: "OE", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 2.0, incentive_weight_1_a: 2.0, incentive_weight_2_a: 2.0, incentive_weight_3_a: 2.0)
    # MO.3
    SchemeCriterion.where(name: "Construction Health & Safety", number: 3, scheme_category: SchemeCategory.where(code: "MO", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 3.0, incentive_weight_1_a: 3.0, incentive_weight_2_a: 3.0, incentive_weight_3_a: 3.0)
    # MO.4
    SchemeCriterion.where(name: "Workers Accommodation", number: 4, scheme_category: SchemeCategory.where(code: "MO", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 4.0, incentive_weight_1_a: 4.0, incentive_weight_2_a: 4.0, incentive_weight_3_a: 4.0)
  end
end
