class AddScoreBToW1 < ActiveRecord::Migration[5.2]
  def change
    SchemeCriterion.where(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], certification_type: Certificate.certification_types[:construction_certificate_stage1], renovation:false))).update_all(weight_a: 3.0, label_a: "Calculated", scores_b: YAML.load("[0, 1, 2, 3]"), minimum_score_b: 0, maximum_score_b: 3, minimum_valid_score_b: 0, weight_b: 3.0, label_b: "Measured")
    SchemeCriterion.where(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], certification_type: Certificate.certification_types[:construction_certificate_stage2], renovation:false))).update_all(weight_a: 3.0, label_a: "Calculated", scores_b: YAML.load("[0, 1, 2, 3]"), minimum_score_b: 0, maximum_score_b: 3, minimum_valid_score_b: 0, weight_b: 3.0, label_b: "Measured")
    SchemeCriterion.where(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], certification_type: Certificate.certification_types[:construction_certificate_stage3], renovation:false))).update_all(weight_a: 3.0, label_a: "Calculated", scores_b: YAML.load("[0, 1, 2, 3]"), minimum_score_b: 0, maximum_score_b: 3, minimum_valid_score_b: 0, weight_b: 3.0, label_b: "Measured")

    SchemeCriterion.where(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.where(code: "W", scheme: Scheme.where(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], renovation:false))).update_all(assign_incentive_manually_a: true, calculate_incentive_a: false, incentive_weight_minus_1_a: 0, incentive_weight_0_a: 0, incentive_weight_1_a: 0, incentive_weight_2_a: 0, incentive_weight_3_a: 0)

    SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], certification_type: Certificate.certification_types[:construction_certificate_stage1], renovation:false))), incentive_weight: 1.0, label: 'Incentive for monitoring domestic water use', display_weight: 1)
    SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], certification_type: Certificate.certification_types[:construction_certificate_stage2], renovation:false))), incentive_weight: 1.0, label: 'Incentive for monitoring domestic water use', display_weight: 1)
    SchemeCriterionIncentive.create!(scheme_criterion: SchemeCriterion.find_by(name: "Domestic Water Use", number: 1, scheme_category: SchemeCategory.find_by(code: "W", scheme: Scheme.find_by(name: "Construction", gsas_document: "GSAS CM_Assessment_2019_11.html", gsas_version: "2019", certificate_type: Certificate.certificate_types[:construction_type], certification_type: Certificate.certification_types[:construction_certificate_stage3], renovation:false))), incentive_weight: 1.0, label: 'Incentive for monitoring domestic water use', display_weight: 1)

  end
end
