class NotificationType < ActiveRecord::Base

  has_many :notification_types_users, dependent: :delete_all

  NEW_USER_COMMENT = 1
  PROJECT_CREATED = 2
  PROJECT_UPDATED = 3
  CERTIFICATE_APPLIED = 4
  CERTIFICATE_ACTIVATED = 5
  CERTIFICATE_SUBMITTED_FOR_SCREENING = 6
  CERTIFICATE_SCREENED = 7
  CERTIFICATE_PCR_SELECTED = 8
  CERTIFICATE_PCR_APPROVED = 9
  CERTIFICATE_SUBMITTED_FOR_VERIFICATION = 10
  CERTIFICATE_VERIFIED = 11
  CERTIFICATE_APPEALED = 12
  CERTIFICATE_APPEAL_APPROVED = 13
  CERTIFICATE_SUBMITTED_FOR_VERIFICATION_AFTER_APPEAL = 14
  CERTIFICATE_VERIFIED_AFTER_APPEAL = 15
  CERTIFICATE_APPROVED_BY_MNGT = 16
  CERTIFICATE_APPROVED_BY_TOP_MNGT = 17
  CERTIFICATE_ISSUED = 18
  CERTIFICATE_REJECTED = 19
  CERTIFICATE_PCR_REQUESTED = 20
  CERTIFICATE_PCR_CANCELED = 21
  CERTIFICATE_PCR_GRANTED = 22
  CERTIFICATE_PCR_REJECTED = 23
  CRITERION_SUBMITTED = 24
  CRITERION_VERIFIED = 25
  CRITERION_APPEALED = 26
  CRITERION_SUBMITTED_AFTER_APPEAL = 27
  CRITERION_VERIFIED_AFTER_APPEAL = 28
  CRITERION_OTHER_STATE_CHANGES = 29
  CRITERION_ASSIGNMENT_CHANGED = 30
  CRITERION_SCORE_CHANGED = 31
  CRITERION_TEXT_CHANGED = 32
  REQUIREMENT_PROVIDED = 33
  REQUIREMENT_OTHER_STATE_CHANGES = 34
  REQUIREMENT_ASSIGNMENT_CHANGED = 35
  NEW_DOCUMENT_WAITING_FOR_APPROVAL = 36
  DOCUMENT_APPROVED = 37
  DOCUMENT_REJECTED = 38
  DOCUMENT_SUPERSEDED = 39
  NEW_TASK = 40
  PROJECT_AUTHORIZATION_CHANGED = 41

  scope :for_user, ->(user_id) {
    joins(:notification_types_users).where(notification_types_users: {user_id: user_id})
  }

  scope :for_project, ->(project_id) {
    joins(:notification_types_users).where(notification_types_users: {project_id: project_id})
  }

  scope :for_general_level, ->() {
    where(project_level: false)
  }

end
